import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Toolbar from "./components/Toolbar/Toolbar";
import AppSidebar from "./components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased d-flex flex-column`}>
        <header className="w-full">
          <Toolbar />
        </header>
        <div className="flex flex-row">
          <AppSidebar />
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
